Feature/db challenge3
Ryu-y-10/quelcode-db pull request #3
Opened 2020-07-20 06:07 UTC by Ryu-y-10

#### DB課題３問題番号001~005

#### やったこと
- SQL文作成
- SQL文実行後、画面キャプチャー画像を各フォルダに格納

2020-07-20 09:12 UTC, piasoratech requested changes
- No002のキャプチャを見ると同じデータが重複して登録されているようなので確認してください。
その他の指摘はコードブロック部分に行いましたので、確認をお願いします

2020-07-20 09:12 UTC, piasoratech commented on db/db-challenge3/db-003/db-003.sql
> +(10, 7,	'2020/04/24 10:55:21'),
体裁を整えましょう

2020-07-20 09:12 UTC, piasoratech commented on db/db-challenge3/db-004/db-004.sql
> +(6,	1, 'test', NULL, 0, 1, '2020/04/26 11:21:44', '2020/04/26 11:21:44'),
体裁を整えましょう

2020-07-20 09:12 UTC, piasoratech commented on db/db-challenge3/db-005/db-005.sql
> +(1, '利用規約をアップロードする', 1, '2020/04/21 14:00:00',	1, 0, 1, 1, '2020/04/21 11:30:55', '2020/04/21 13:13:20'),
体裁を整えましょう

2020-07-20 09:12 UTC, piasoratech commented on db/db-challenge3/db-006/db-006.sql
> +SELECT user_id, user_name, email_address, password, profile, work_phone_number, personal_mobile_number, is_deleted, created_at, updated_at
Sliteに記載されている決まりは守りましょう。

2020-07-20 22:38 UTC, Ryu-y-10 commented
全てのファイルの値と値の間のスペースを取り除くことで統一し体裁を整え作業後、カンマ半角スペース、全角スペースで検索をして消し忘れなど無いようチェックを入れました。
ルールについて失念しており大変申し訳ありませんでした。pushしたファイルについては削除しました。

2020-07-21 04:19 UTC, Yuzunoha commented
おしい1点だけ！
DB課題3 SS 003-02.png のキャプチャのレコードの表示件数が足りないので、レコードの表示件数を増やしてとり直しをお願いします。

2020-07-21 04:33 UTC, Ryu-y-10 commented
#### 指摘箇所修正しました
- ファイルを削除し、表示件数を全て表示してから画面をキャプチャーし直しました。

2020-07-21 05:22 UTC, Yuzunoha commented
レビュー遅れてすみません！
001~005 OKです！

2020-07-28 02:55 UTC, piasoratech requested changes
コメントしたので確認をお願いします！
No004で指摘漏れがあった関係でNo006～No010に影響がある可能性が高いので、
No004のデータを修正後もう一度各SQLを実行してもらい、結果が異なる場合はキャプチャの差し替えをお願いします。

2020-07-28 02:55 UTC, piasoratech commented on db/db-challenge3/db-006/db-006.sql
> +WHERE is_deleted IN(0,1) ORDER BY user_id ASC;
WHERE句は必ず書かなければいけないものではないので、この場合のWHERE句は不要です。

2020-07-28 02:55 UTC, piasoratech commented on db/db-challenge3/db-004/db-004.sql
> +(7,10,'sss',NULL,0,10,'2020/04/26 18:09:37','2020/04/26 17:11:23');
このデータが間違っていたので、内容確認の上修正をお願いします。
指摘漏れてて申し訳ないです。

2020-07-28 04:07 UTC, Ryu-y-10 commented
#### 指摘箇所の修正を行いました
- 問題番号004 ：指摘箇所の値の変更、再度SQL実行結果をキャプチャー(55af008)(0cd8963)
- 問題番号006 ：不必要なWHERE句の削除、再度SQL実行結果をキャプチャー(6d3106c)(1987090)
- 問題番号008 ：指摘箇所とは別件ですがSQL実行結果が全件キャプチャーできていなかったので再度キャプチャーし直しました(28737cf)
- 問題番号009、010 ：問題番号004修正に伴いSQL実行結果を再度キャプチャーし直しました(21a0523)(4427b93)

2020-07-28 04:41 UTC, piasoratech requested changes
No010が違うので確認と修正をお願いします。

2020-07-28 06:19 UTC, Ryu-y-10 commented
#### 指摘箇所修正を行いました
- 問題番号010
条件の当てはまる各ルームの投稿者名、最新投稿日時、ルーム名を表示するように修正しました(54fe1e5)
SQL文実行結果の画面を再度キャプチャーしました(4962dd9)

2020-07-28 06:31 UTC, piasoratech reviewed
No006～No010までOKです
次に進みましょう！

2020-07-30 00:34 UTC, Yuzunoha approved these changes
011~014 OKです！！！

2020-07-30 02:54 UTC, merged